language: cpp

sudo: false

matrix:
    include:
      - os: osx
        osx_image: xcode9.1
        compiler: clang

      - os: linux
        compiler: g++
 
      - os: linux
        compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.6
      - llvm-3.6   
      - libgtest-dev 
    env:
  global:
    - USE_CCACHE=1

before_install:
#debug travis errs
  -  ls -l $HOME
install:
 #nope
before_script:
    - ./travis_rebuild_cache.sh
    - ls -l $HOME/build/
    - ls -l $HOME/include/
    - ls -l $HOME/lib/
script:
#  - g++ --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "g++" ]; then export CXX="/usr/bin/g++-4.9" CC="gcc-4.9"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "clang++" ]; then export CXX="/usr/bin/clang++-3.6" CC="clang-3.6"; fi
#  - $CXX --version  
#  - echo $CXX
#     - which g++-4.9i
#  - ccache -s
  - mkdir -p build && cd build && cmake -DBOOST_INCLUDEDIR=${HOME}/include .. #-DBamtools_PREFIX=${HOME}/ ..
  - make
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd test &&  ./UnitTests; fi
cache:
    directories:
    - $HOME/lib/
    - $HOME/include/
    - $HOME/.ccache
